# $snake = /home/kuroiko/Pictures/Wallpapers/snake.png
$fg2 = rgba(d5c4a1ff)
$bg0 = rgba(1d2021cc)

general {
    hide_cursor = true
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = ~/.curr_wall_static.jpg
    blur_passes = 3
    blur_size = 8
    brightness = 0.55
    noise = 0.0117
    contrast = 0.9
}

input-field {
    monitor =
    size = 300, 60
    outline_thickness = 3
    dots_size = 0.26
    dots_spacing = 0.35
    dots_center = true
    outer_color = $fg2
    inner_color = $bg0
    font_color = $fg2
    fade_on_empty = true
    placeholder_text = <span foreground="##d5c4a1">Password...</span>
    hide_input = false
    position = 0, -140
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = $fg2
    font_size = 90
    font_family = Google Sans Flex Medium
    position = 0, 160
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] echo "$(date +"%A, %B %d")"
    color = $fg2
    font_size = 22
    font_family = Google Sans Flex Medium
    position = 0, 90
    halign = center
    valign = center
}
