-- Generated by nwg-displays on 2026-06-09 at 15:10:30. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1200@59.99",
    position = "0x0",
    scale = 1.0,
    mirror = "eDP-1"
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "3840x2160@30.0",
    position = "1920x0",
    scale = 1.0,
    mirror = "eDP-1"
})
